### ISSUE TITLE
Allow wild card * in filtering

### ISSUE THREAD

**Issue by adhendrikx** [hendrikx-itc/3gpp-xml-cm-splitter#2]
## Why
For more flexible filtering.

## How
When 'enb032851' is stated as filter argument all elements with matching name 'enb032851' should be returned.

When 'enb0328*' is stated all elements with name starting with 'enb0328' should be returned.

## DoD
Evidence in in comments (output)

**Comment by Mastermees** [comment]
Resolved in commit ff01db7ba0eec8104a6e195a12639b3d3ba72760.

**Comment by Mastermees** [comment]
![image](https://user-images.githubusercontent.com/92491954/168240593-8cf697eb-bd98-45e7-a167-f232bd746271.png)
